### ISSUE TITLE
loading the latest versions of icd10cm causes an error.

### ISSUE THREAD

**Issue by phil-dorsata** [WestCoastInformatics/UMLS-Terminology-Server#1]
Hey there,

So starting with a clean database, I've attempted to load the 2016 version of icd10cm. I've downloaded the file from the following location: http://apps.who.int/classifications/apps/icd/ClassificationDownloadNR/list.htm

and I'm using the following loader command (note that the createdb task has already been run successfully) `mvn install -PClaML -Drun.config.ts=<ourconfigdir>/config.properties -Dterminology=ICD10CM -Dversion=latest -Dinput.file=<ourdatadir>/icdClaML2016ens.xml`

this seems to work pretty well, (one quirk is that i had to put the ClaML.dtd file that was included with the icd10cm download into the loader directory before running the loader command).

However, the loading fails towards the end. It appears that some records  aren't being saved properly (note the abundance of "null" in the stack trace, presumably where the id should be)

Questions
- Is this a known issue? 
- should I stick with the 2014 version of icd10cm for now? (the 2015 version appears to cause the same issue as described above). 
- is there a expected timeline for 2016 icd10cm support?

P.S sorry about the formatting

2016-09-08_15:37:46.498 INFO -   Create Relationship E78.8 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.1 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.2 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.3 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.9 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.0 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.6 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.4 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship E78.5 isa E78 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.4 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.1 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.2 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.5 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.0 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.6 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Relationship D07.3 isa D07 null
2016-09-08_15:37:46.498 INFO -   Create Reference Relationship H67.0 † (dagger) A18.6 D0006904
2016-09-08_15:37:46.498 INFO -   Create Relationship S80.1 isa S80 null
2016-09-08_15:37:46.498 INFO -   Create Relationship S80.7 isa S80 null
2016-09-08_15:37:46.498 INFO -   Create Relationship S80.9 isa S80 null
2016-09-08_15:37:46.498 INFO -   Create Relationship S80.0 isa S80 null
2016-09-08_15:37:46.498 INFO -   Create Relationship S80.8 isa S80 null
2016-09-08_15:37:46.498 INFO -   Create Reference Relationship N22.0 † (dagger) B65 D0011277
2016-09-08_15:37:46.498 INFO -   Create Reference Relationship R23.3 reference P54.5 id-to-be-added-later-1210506823253-4515
2016-09-08_15:37:46.498 INFO - Load Concepts and Atoms
2016-09-08_15:37:46.528 INFO -     count = 0
2016-09-08_15:38:07.115 INFO -     count = 2000
2016-09-08_15:38:14.743 INFO -     count = 4000
2016-09-08_15:38:21.866 INFO -     count = 6000
2016-09-08_15:38:27.222 INFO -     count = 8000
2016-09-08_15:38:31.752 INFO -     count = 10000
2016-09-08_15:38:35.964 INFO -     count = 12000
2016-09-08_15:38:40.727 INFO -     count = 14000
2016-09-08_15:38:45.059 INFO -     count = 16000
2016-09-08_15:38:49.480 INFO -     count = 18000
2016-09-08_15:38:52.968 INFO - Load Atom Relationships
2016-09-08_15:38:53.446 WARN - HHH000437: Attempting to save one or more entities that have a non-nullable association with an unsaved transient entity. The unsaved transient entity must be saved in an operation prior to saving these dependent entities.
        Unsaved transient entity: ([com.wci.umls.server.jpa.content.AtomJpa#<null>])
        Dependent entities: ([[com.wci.umls.server.jpa.content.AtomRelationshipJpa#211600]])
        Non-nullable association(s): ([com.wci.umls.server.jpa.content.AtomRelationshipJpa.from])
        Dependent entities: ([[com.wci.umls.server.jpa.content.AtomRelationshipJpa#211600]])                                                                                                                        Non-nullable association(s): ([com.wci.umls.server.jpa.content.AtomRelationshipJpa.from])
org.xml.sax.SAXException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.wci.umls.server.jpa.content.AtomRelationshipJpa.from -> com.wci.umls.server.jpa.content.AtomJpa
java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.wci.umls.server.jpa.content.AtomRelationshipJpa.from -> com.wci.umls.server.jpa.content.AtomJpa
        at com.wci.umls.server.jpa.algo.ClamlLoaderAlgorithm$LocalHandler.endDocument(ClamlLoaderAlgorithm.java:1164)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:745)
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endDocument(XMLDTDValidator.java:928)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:509)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at com.wci.umls.server.jpa.algo.ClamlLoaderAlgorithm.compute(ClamlLoaderAlgorithm.java:231)
        at com.wci.umls.server.rest.impl.ContentServiceRestImpl.loadTerminologyClaml(ContentServiceRestImpl.java:591)
        at com.wci.umls.server.mojo.TerminologyClamlLoaderMojo.execute(TerminologyClamlLoaderMojo.java:121)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.wci.umls.server.jpa.content.AtomRelationshipJpa.from -> com.wci.umls.server.jpa.content.AtomJpa at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.wci.umls.server.jpa.content.AtomRelationshipJpa.from -> com.wci.umls.server.jpa.content.AtomJpa
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1760)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1187)
        at com.wci.umls.server.jpa.services.ContentServiceJpa.addComponent(ContentServiceJpa.java:4115)
        at com.wci.umls.server.jpa.services.ContentServiceJpa.addRelationship(ContentServiceJpa.java:2363)
        at com.wci.umls.server.jpa.algo.ClamlLoaderAlgorithm$LocalHandler.endDocument(ClamlLoaderAlgorithm.java:1140)
        ... 33 more
Caused by: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.wci.umls.server.jpa.content.AtomRelationshipJpa.from -> com.wci.umls.server.jpa.content.AtomJpa
        at org.hibernate.action.internal.UnresolvedEntityInsertActions.checkNoUnresolvedActionsAfterOperation(UnresolvedEntityInsertActions.java:137)
        at org.hibernate.engine.spi.ActionQueue.checkNoUnresolvedActionsAfterOperation(ActionQueue.java:320)
        at org.hibernate.internal.SessionImpl.checkNoUnresolvedActionsAfterOperation(SessionImpl.java:658)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:813)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
        ... 36 more
java.lang.Exception: Conversion of Claml to RF2 objects failed
        at com.wci.umls.server.jpa.algo.ClamlLoaderAlgorithm.compute(ClamlLoaderAlgorithm.java:263)
        at com.wci.umls.server.rest.impl.ContentServiceRestImpl.loadTerminologyClaml(ContentServiceRestImpl.java:591)
        at com.wci.umls.server.mojo.TerminologyClamlLoaderMojo.execute(TerminologyClamlLoaderMojo.java:121)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by bcarlsenca** [comment]
Phil,

Very interesting to get a reply about our terminology server work this.  Yeah, for the DTD thing, I usually just remove the compliance line so that it doesn’t require DTD for checking and I assume the ClaML is valid.

Your link for ICD10 is actually to the WHO international edition of ICD10 and not the ICD10CM used in the US.  For that you want to use this link: https://www.cms.gov/Medicare/Coding/ICD10/2016-ICD-10-CM-and-GEMs.html

(It’s the second link: https://www.cms.gov/Medicare/Coding/ICD10/Downloads/2016-CM-Code-Tables-and-Index.zip)

Also, the ICD10CM doesn’t come in ClaML, I have a converter so that I can reuse the same loader (see attached).

Let me download the file, do the ClaML conversion and get this running in a clean environment, and I’ll get you a config.properties that works with that as well as a ClaML file that loads properly.  This is all a little tricky.

Reply to this so I can email you at your real address and not redirected thru github.

Brian

bcarlsen@westcoastinformatics.com

**Comment by bcarlsenca** [comment]
OK, 

Hopefully you’re getting these messages.

So, I took the liberty of converting the ICD10CM 2016 files to Claml using the attached converter script.  I then edited to remove the DTD declaration and make sure the “version” field in the header was properly set ( because the script attempts to extract it from the filename).

In any case, I was able to successfully load this with essentially the config.properties file from the config/prod-claml (but with paths for my environment).

The result is deployed on https://icd.terminology.tools (which requires a UTS account to log in).

I added the script and the updated .xml file to the project (master branch) on github.  Let me know if you have any other questions.

Brian Carlsen

West Coast Informatics, LLC

 http://www.westcoastinformatics.com/ http://www.westcoastinformatics.com

(510) 854-6401

 https://www.linkedin.com/in/bcarlsenca Personal LinkedIn

 https://www.linkedin.com/company/2925322 Company LinkedIn

**Comment by bcarlsenca** [comment]
I sent a couple of replies but they contained attachments that may have been blocked on your end.  Let me know if you didn’t receive other email from me and I’ll rewrite the attachment.

Brian

**Comment by phil-dorsata** [comment]
Hey, thanks a lot for the reply! This sounds awesome, ill give it a shot.
